### ISSUE TITLE
Project create, empty fields

### ISSUE THREAD

**Issue by unref** [itJunky/web-tasker.py#18]
При добавление нового проекта в БД, добавляется запись с пустыми полями `status` и `owner`.

https://github.com/itJunky/web-tasker.py/blob/c07c2b12f2e805124ebacaed426ad08904959d3a/web_tasker/views.py#L289

**Comment by itJunky** [comment]
Проверил на проде?

**Comment by unref** [comment]
На проде мне никак не проверить, локально у меня все работает.
