### ISSUE TITLE
Task list exception

### ISSUE THREAD

**Issue by unref** [itJunky/web-tasker.py#19]
Выбрасывается исключение если пользователь разлогинен, локальные куки потерты и выполнить переход на ендпоинт `task`.

IndexError: list index out of range

https://github.com/itJunky/web-tasker.py/blob/c07c2b12f2e805124ebacaed426ad08904959d3a/web_tasker/views.py#L55

https://github.com/itJunky/web-tasker.py/blob/c07c2b12f2e805124ebacaed426ad08904959d3a/web_tasker/views.py#L625

**Comment by itJunky** [comment]
По идее был отлов подобного в других эндпоинтах, для фикса достаточно везде расставить просто.

В любом случае надо проверить помогло ли.

**Comment by unref** [comment]
Этой баги больше нет. В настоящем проетке теперь перенаправляет на форму логина. Закрываю.
