### ISSUE TITLE
"Add comment" form bug

### ISSUE THREAD

**Issue by VladimirBulanov** [itJunky/web-tasker.py#6]
Форма добавления комментария к задаче не валидируется корректно. Добавляется пустой комментарий.

**Comment by itJunky** [comment]
Нашёл вариантик неплохой на стековерфлоу https://stackoverflow.com/questions/12164751/check-input-value-length

Осталось добавить к этому выпадающий алерт или ещё какое предупреждение и задача будет решена.

**Comment by itJunky** [comment]
Fixed by https://github.com/itJunky/web-tasker.py/pull/11

**Comment by itJunky** [comment]
Prod updated
